### ISSUE TITLE
wiki dump script has an import error for yaml

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/roswiki#153]
It continues but effects at least one page. 

```
Writing "ROS(2f)CommandLineTools.html"...
2016-02-08 18:07:57,737 ERROR MoinMoin.macro:132 Macro TableOfContents (page: 'ROS/CommandLineTools') raised an exception:
Traceback (most recent call last):
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/macro/__init__.py", line 122, in execute
    return execute(self, args)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/macro/__init__.py", line 107, in <lambda>
    _self.request, call, _args, [_self])
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/wikiutil.py", line 1962, in invoke_extension_function
    return function(*fixed_args, **kwargs)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/macro/TableOfContents.py", line 166, in macro_TableOfContents
    omit_footnotes=True)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/web/contexts.py", line 296, in redirectedOutput
    function(*args, **kw)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/Page.py", line 1215, in send_page
    start_line=pi['lines'])
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/Page.py", line 1305, in send_page_content
    self.format(parser)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/Page.py", line 1326, in format
    parser.format(self.formatter)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/parser/text_moin_wiki.py", line 1554, in format
    formatted_line = self.scan(line, inhibit_p=inhibit_p)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/parser/text_moin_wiki.py", line 1364, in scan
    result.append(self.replace(match, inhibit_p))
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/parser/text_moin_wiki.py", line 1408, in replace
    result.append(replace_func(hit, match.groupdict()))
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/parser/text_moin_wiki.py", line 1331, in _macro_repl
    return self.formatter.macro(self.macro, macro_name, macro_args, markup=groups.get('macro'))
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/macro/TableOfContents.py", line 71, in macro
    name, 'generates_headings')
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/wikiutil.py", line 1063, in importPlugin
    return importWikiPlugin(cfg, kind, name, function)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/wikiutil.py", line 1078, in importWikiPlugin
    return importNameFromPlugin(moduleName, function)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/wikiutil.py", line 1102, in importNameFromPlugin
    module = __import__(moduleName, globals(), {}, fromlist)
  File "/var/www/wiki.ros.org/data/plugin/macro/Version.py", line 34, in <module>
    from headers import distro_html
  File "/var/www/wiki.ros.org/data/plugin/macro/headers.py", line 11, in <module>
    from macroutils import CONTRIBUTE_TMPL
  File "/var/www/wiki.ros.org/data/plugin/macro/macroutils.py", line 5, in <module>
    import yaml
ImportError: No module named yaml
*** Caught exception while writing page!
Writing "ROS(2f)CommandLineTools(2f)Review.html"...
```

**Comment by tfoote** [comment]
This might be the cause of the reported errors from VC on the mailing list: 
``
In case somebody hasn't already flagged it, just to let you know that the wiki mirroring still seems to have a glitch (see this page, for e.g. http://mirror-ap.wiki.ros.org/common_msgs.html); some pages are fine (for e.g. http://mirror-ap.wiki.ros.org/3d_navigation.html). HTH.
```

**Comment by tfoote** [comment]
The virtual env running the dump script was missing pyyaml and clearsilver. I added them and ran the [dump script](https://github.com/ros-infrastructure/roswiki/blob/wiki_dump_script/dump_wiki) manually without these exceptions occurring.

**Comment by vcravi** [comment]
Thanks for the effort to get this closed! It makes a world of difference when referring to the wiki offline!
